/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface EmployeeCard {
        "currencySymbol": string;
        "endPoint": string;
    }
}
declare global {
    interface HTMLEmployeeCardElement extends Components.EmployeeCard, HTMLStencilElement {
    }
    var HTMLEmployeeCardElement: {
        prototype: HTMLEmployeeCardElement;
        new (): HTMLEmployeeCardElement;
    };
    interface HTMLElementTagNameMap {
        "employee-card": HTMLEmployeeCardElement;
    }
}
declare namespace LocalJSX {
    interface EmployeeCard {
        "currencySymbol"?: string;
        "endPoint"?: string;
    }
    interface IntrinsicElements {
        "employee-card": EmployeeCard;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "employee-card": LocalJSX.EmployeeCard & JSXBase.HTMLAttributes<HTMLEmployeeCardElement>;
        }
    }
}
